### ISSUE TITLE
Installation will not proceed at 70%

### ISSUE THREAD

**Issue by ShneepShneep** [gerlofvanek/basicswap-Installation-GUI#25]
The installation will not proceed beyond this point. Any way to fix this?

![Capture](https://github.com/gerlofvanek/basicswap-installation-GUI/assets/170232361/d8d34b82-ba3c-4255-9aa7-5d8c3fbc12fe)

**Comment by BataraSambu** [comment]
got the same

**Comment by CrispyPorkGang** [comment]
> The installation will not proceed beyond this point. Any way to fix this?
> 
> ![Capture](https://private-user-images.githubusercontent.com/170232361/334585426-d8d34b82-ba3c-4255-9aa7-5d8c3fbc12fe.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NjI4ODQsIm5iZiI6MTcxNzU2MjU4NCwicGF0aCI6Ii8xNzAyMzIzNjEvMzM0NTg1NDI2LWQ4ZDM0YjgyLWJhM2MtNDI1NS05YWE3LTVkOGMzZmJjMTJmZS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQwNDQzMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjQwMzA4NWY3OTM1ZWViMmFjODg1MDQyOGUwZmUyZTBkZjZiZjNhZmRiMDg0YmYwNDI0YzIwOGFjNDhlMjFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1XW4CquvIDly5YVoaCtPP-CzA9vnE1l4XKxAyj3O6-M)

When you build the basic swap installer go to .\electron-gui\build\
edit the basic swap install window. remove installing protoc and protobuf. theres an issue with the installer, installing an older version of protobuf which removes it from PATH. make sure you install protobuf manually and everything should work

**Comment by tebulot** [comment]
Yeah same deal here, windows install.

**Comment by privacyguy123** [comment]
> > The installation will not proceed beyond this point. Any way to fix this?
> > ![Capture](https://private-user-images.githubusercontent.com/170232361/334585426-d8d34b82-ba3c-4255-9aa7-5d8c3fbc12fe.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NjI4ODQsIm5iZiI6MTcxNzU2MjU4NCwicGF0aCI6Ii8xNzAyMzIzNjEvMzM0NTg1NDI2LWQ4ZDM0YjgyLWJhM2MtNDI1NS05YWE3LTVkOGMzZmJjMTJmZS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQwNDQzMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjQwMzA4NWY3OTM1ZWViMmFjODg1MDQyOGUwZmUyZTBkZjZiZjNhZmRiMDg0YmYwNDI0YzIwOGFjNDhlMjFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1XW4CquvIDly5YVoaCtPP-CzA9vnE1l4XKxAyj3O6-M)
> 
> When you build the basic swap installer go to .\electron-gui\build edit the basic swap install window. remove installing protoc and protobuf. theres an issue with the installer, installing an older version of protobuf which removes it from PATH. make sure you install protobuf manually and everything should work

Thanks, worked. You should submit a PR to remove protobuf from WIndows install script.

**Comment by gerlofvanek** [comment]
Update coming up in the next few days. It will fix the "not proceed at 70%" and removed the protobuff.,and it will add wownero/decred in the installer as coin select option and various other fixes.

**Comment by tebulot** [comment]
> Update coming up in the next few days. It will fix the "not proceed at 70%" and removed the protobuff.,and it will add wownero/decred in the installer as coin select option and various other fixes.

Yeah awesome, I'm here for wownero specifically so will wait out :p

**Comment by gerlofvanek** [comment]
Try: https://github.com/gerlofvanek/basicswap-installation-GUI/releases/tag/WIN-v3.0.0 Its still pre-release.

**Comment by tebulot** [comment]
Had a go, it still stalls at 70% funnily enough but it also says that the installation was completed.

After running the batch file as admin it ends up just closing out. I'm following along on the batch and I think my issue is it never spins up the Python virtual environment.

Hm... okay, so I can run the activate script manually, when running powershell as an admin. I think for some reason the permissions aren't carrying across to spinning up the venv

And this is what I get after running:
cd "C:\Users\TRISMEGISTUS\Desktop\WOWNERO\BS2\basicswap"
basicswap-run --datadir="C:\Users\TRISMEGISTUS\Desktop\WOWNERO\BS2\coindata"

--

(venv) PS C:\Users\TRISMEGISTUS\Desktop\WOWNERO\BS2\basicswap> basicswap-run --datadir="C:\Users\TRISMEGISTUS\Desktop\WOWNERO\BS2\coindata"
WARNING:root:Running on windows is discouraged and windows support may be discontinued in the future.  Please consider using the WSL docker setup instead.
INFO:root:Using datadir: C:\Users\TRISMEGISTUS\Desktop\WOWNERO\BS2\coindata
INFO:root:Chain: mainnet
INFO:root:basicswap-run, version: 0.13.4


Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\basicswap-run.exe\__main__.py", line 7, in <module>
  File "C:\Python312\Lib\site-packages\bin\basicswap_run.py", line 443, in main
    runClient(fp, data_dir, chain, start_only_coins)
  File "C:\Python312\Lib\site-packages\bin\basicswap_run.py", line 185, in runClient
    raise ValueError('Settings file not found: ' + str(settings_path))
ValueError: Settings file not found: C:\Users\TRISMEGISTUS\Desktop\WOWNERO\BS2\coindata\basicswap.json

--

Yeah I'm not sure what's going wrong here

**Comment by gerlofvanek** [comment]
> Had a go, it still stalls at 70% funnily enough but it also says that the installation was completed.
> 
> After running the batch file as admin it ends up just closing out. I'm following along on the batch and I think my issue is it never spins up the Python virtual environment.
> 
> Hm... okay, so I can run the activate script manually, when running powershell as an admin. I think for some reason the permissions aren't carrying across to spinning up the venv
> 
> And this is what I get after running: cd "C:\Users\TRISMEGISTUS\Desktop\WOWNERO\BS2\basicswap" basicswap-run --datadir="C:\Users\TRISMEGISTUS\Desktop\WOWNERO\BS2\coindata"
> 
> --
> 
> (venv) PS C:\Users\TRISMEGISTUS\Desktop\WOWNERO\BS2\basicswap> basicswap-run --datadir="C:\Users\TRISMEGISTUS\Desktop\WOWNERO\BS2\coindata" WARNING:root:Running on windows is discouraged and windows support may be discontinued in the future. Please consider using the WSL docker setup instead. INFO:root:Using datadir: C:\Users\TRISMEGISTUS\Desktop\WOWNERO\BS2\coindata INFO:root:Chain: mainnet INFO:root:basicswap-run, version: 0.13.4
> 
> Traceback (most recent call last): File "", line 198, in _run_module_as_main File "", line 88, in _run_code File "C:\Python312\Scripts\basicswap-run.exe__main__.py", line 7, in File "C:\Python312\Lib\site-packages\bin\basicswap_run.py", line 443, in main runClient(fp, data_dir, chain, start_only_coins) File "C:\Python312\Lib\site-packages\bin\basicswap_run.py", line 185, in runClient raise ValueError('Settings file not found: ' + str(settings_path)) ValueError: Settings file not found: C:\Users\TRISMEGISTUS\Desktop\WOWNERO\BS2\coindata\basicswap.json
> 
> --
> 
> Yeah I'm not sure what's going wrong here
Thanks, do you also have the debug or screenshot of the installer installing?

**Comment by tebulot** [comment]
Yeah sure mate:

##############################################################################
# Check if running as administrator.
##############################################################################
##############################################################################
# 0 Uninstall Dependencies.
##############################################################################
[INFO] Uninstalling dependencies...
[INFO] python3 not found, skipping...
[INFO] protoc not found, skipping...
[INFO] curl not found, skipping...
[INFO] jq not found, skipping...
[INFO] wget not found, skipping...
[INFO] gnupg not found, skipping...
[INFO] git not found, skipping...
[INFO] Finished uninstalling dependencies.
##############################################################################
# 1 Installing Dependencies.
##############################################################################
[INFO] Installing required dependencies...
PROGRESS: 5
[INFO] Chocolatey already installed.
[INFO] Check if older versions of Python exist and remove them
[INFO] Installing python, protoc, curl, jq, wget, gnupg, git via Chocolatey...
Chocolatey v2.3.0 Installing the following packages: python3;protoc;curl;jq;wget;gnupg;git;protobuf By installing, you accept licenses for the packages. python3 v3.12.4 already installed.  Use --force to reinstall, specify a version to install, or try upgrade. protoc v27.1.0 already installed.  Use --force to reinstall, specify a version to install, or try upgrade. curl v8.8.0 already installed.  Use --force to reinstall, specify a version to install, or try upgrade. jq v1.7.1 already installed.  Use --force to reinstall, specify a version to install, or try upgrade. Wget v1.21.4 already installed.  Use --force to reinstall, specify a version to install, or try upgrade. gnupg v2.4.5 already installed.  Use --force to reinstall, specify a version to install, or try upgrade. git v2.45.2 already installed.  Use --force to reinstall, specify a version to install, or try upgrade. protobuf not installed. The package was not found with the source(s) listed.  Source(s): 'https://community.chocolatey.org/api/v2/'  NOTE: When you specify explicit sources, it overrides default sources. If the package version is a prerelease and you didn't specify `--pre`,  the package may not be found. Please see https://docs.chocolatey.org/en-us/troubleshooting for more  assistance.  Chocolatey installed 0/8 packages. 1 packages failed.  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).  Warnings:  - curl - curl v8.8.0 already installed.  Use --force to reinstall, specify a version to install, or try upgrade.  - git - git v2.45.2 already installed.  Use --force to reinstall, specify a version to install, or try upgrade.  - gnupg - gnupg v2.4.5 already installed.  Use --force to reinstall, specify a version to install, or try upgrade.  - jq - jq v1.7.1 already installed.  Use --force to reinstall, specify a version to install, or try upgrade.  - protoc - protoc v27.1.0 already installed.  Use --force to reinstall, specify a version to install, or try upgrade.  - python3 - python3 v3.12.4 already installed.  Use --force to reinstall, specify a version to install, or try upgrade.  - Wget - Wget v1.21.4 already installed.  Use --force to reinstall, specify a version to install, or try upgrade.  Failures  - protobuf - protobuf not installed. The package was not found with the source(s) listed.  Source(s): 'https://community.chocolatey.org/api/v2/'  NOTE: When you specify explicit sources, it overrides default sources. If the package version is a prerelease and you didn't specify `--pre`,  the package may not be found. Please see https://docs.chocolatey.org/en-us/troubleshooting for more  assistance.
PROGRESS: 10
[INFO] Creating a Python virtual environment...
[INFO] Activating the virtual environment...
[INFO] Virtual environment activated!
##############################################################################
# 2 Start of script.
##############################################################################
[INFO] Checking and installing prerequisites...
[INFO] INSTALL_PATH: C:\Users\TRISMEGISTUS\Desktop\BS
[INFO] SELECTED_COINS: Wownero
PROGRESS: 15
##############################################################################
# 3 User selected installation path and selected coins.
##############################################################################
[INFO] Please enter the absolute path to the directory where you wish to install BasicSwap: C:\Users\TRISMEGISTUS\Desktop\BS
[INFO] Please choose the coins you want to include (separate with commas, no spaces): Wownero
PROGRESS: 20
##############################################################################
# 4 Validate selected coins input
##############################################################################
[INFO] Validating selected coins input.
Selected coins input validated successfully.
##############################################################################
# 5 Set up the coins data directory.
##############################################################################
[INFO] Setting up the coins data directory...
[INFO] The path to the coins data dirs folder is C:\Users\TRISMEGISTUS\Desktop\BS\coindata
PROGRESS: 25
##############################################################################
# 6 Check if the coins data directory exists.
##############################################################################
[INFO] Checking if the coins data directory exists...
PROGRESS: 30


    Directory: C:\Users\TRISMEGISTUS\Desktop\BS


Mode                 LastWriteTime         Length Name                                                                 
----                 -------------         ------ ----                                                                 
d-----        20/07/2024   8:54 AM                coindata                                                             
PROGRESS: 35
##############################################################################
# 7 Check if Python is installed, and if not, install required dependencies.
##############################################################################
[INFO] Checking if Python is installed...
[INFO] Python detected: Python 3.12.4
PROGRESS: 40
##############################################################################
# Part 1 completed. Running Part 2
##############################################################################


Child process exited with code 0
##############################################################################
# 8 Set up Python virtual environment.
##############################################################################
[INFO] Setting up Python virtual environment...
[INFO] Python virtual environment already exists.
PROGRESS: 40
##############################################################################
# 10 Cloning and setting up coincurve from tecnovert's GitHub fork.
##############################################################################
[INFO] Cloning and setting up coincurve from tecnovert's GitHub fork...
[ALERT]: Cloning into 'C:\Users\TRISMEGISTUS\Desktop\BS\coindata\coincurve-tecnovert'...

Processing c:\users\trismegistus\desktop\bs\coindata\coincurve-tecnovert
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: asn1crypto in c:\python312\lib\site-packages (from coincurve==18.0.3) (1.5.1)
Requirement already satisfied: cffi>=1.3.0 in c:\python312\lib\site-packages (from coincurve==18.0.3) (1.16.0)
Requirement already satisfied: pycparser in c:\python312\lib\site-packages (from cffi>=1.3.0->coincurve==18.0.3) (2.22)
Building wheels for collected packages: coincurve
  Building wheel for coincurve (pyproject.toml): started
  Building wheel for coincurve (pyproject.toml): finished with status 'done'
  Created wheel for coincurve: filename=coincurve-18.0.3-py3-none-any.whl size=1571992 sha256=c220d11c7956cdc8c28e49a2226f9ce537261570dca13e1594bea7429d2f5959
  Stored in directory: c:\users\trismegistus\appdata\local\pip\cache\wheels\db\46\93\67db2cae36240581896ec6aa4f31fc36134d6032b27f5ec8c0
Successfully built coincurve
Installing collected packages: coincurve
  Attempting uninstall: coincurve
    Found existing installation: coincurve 18.0.3
    Uninstalling coincurve-18.0.3:
      Successfully uninstalled coincurve-18.0.3
Successfully installed coincurve-18.0.3
[ALERT]: 
[
[ALERT]: notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

[INFO] Successfully installed coincurve from tecnovert's fork.
PROGRESS: 50
##############################################################################
# 11 Cloning and setting up BasicSwap from GitHub.
##############################################################################
[INFO] Cloning and setting up BasicSwap from GitHub...
[ALERT]: Cloning into 'C:\Users\TRISMEGISTUS\Desktop\BS\basicswap'...

[INFO] Installing required Python packages for BasicSwap...
Processing c:\users\trismegistus\desktop\bs\basicswap
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: wheel in c:\python312\lib\site-packages (from basicswap==0.13.4) (0.43.0)
Requirement already satisfied: pyzmq in c:\python312\lib\site-packages (from basicswap==0.13.4) (26.0.3)
Requirement already satisfied: sqlalchemy==1.4.39 in c:\python312\lib\site-packages (from basicswap==0.13.4) (1.4.39)
Requirement already satisfied: python-gnupg in c:\python312\lib\site-packages (from basicswap==0.13.4) (0.5.2)
Requirement already satisfied: Jinja2 in c:\python312\lib\site-packages (from basicswap==0.13.4) (3.1.4)
Requirement already satisfied: pycryptodome in c:\python312\lib\site-packages (from basicswap==0.13.4) (3.20.0)
Requirement already satisfied: PySocks in c:\python312\lib\site-packages (from basicswap==0.13.4) (1.7.1)
Requirement already satisfied: greenlet!=0.4.17 in c:\python312\lib\site-packages (from sqlalchemy==1.4.39->basicswap==0.13.4) (3.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in c:\python312\lib\site-packages (from Jinja2->basicswap==0.13.4) (2.1.5)
Building wheels for collected packages: basicswap
  Building wheel for basicswap (pyproject.toml): started
  Building wheel for basicswap (pyproject.toml): finished with status 'done'
  Created wheel for basicswap: filename=basicswap-0.13.4-py3-none-any.whl size=4604563 sha256=dce4b50ca5119497cf4b32d8c67ff00f54bd5521fd1895992f3856b9eea64a24
  Stored in directory: C:\Users\TRISMEGISTUS\AppData\Local\Temp\pip-ephem-wheel-cache-1x0egif2\wheels\68\74\64\c53c5a21f60d304be712890fe46f3c919e4082e25505138a38
Successfully built basicswap
Installing collected packages: basicswap
  Attempting uninstall: basicswap
    Found existing installation: basicswap 0.13.4
    Uninstalling basicswap-0.13.4:
      Successfully uninstalled basicswap-0.13.4
Successfully installed basicswap-0.13.4
[ALERT]: 
[notice]
[ALERT]:  A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

PROGRESS: 60
##############################################################################
# 12 Preparing Basicswap.
##############################################################################
[INFO] Preparing BasicSwap...
[INFO] Preparing BasicSwap.
PROGRESS: 70
[INFO] Starting basicswap-prepare. This might take a while...
[ALERT]: INFO:root:BasicSwap prepare script 0.13.4

INFO:root:Python version: 3.12.4
INFO:root:Data dir: C:\Users\TRISMEGISTUS\Desktop\BS\coindata
INFO:root:Bin dir: C:\Users\TRISMEGISTUS\Desktop\BS\coindata\bin
INFO:root:Chain: mainnet
INFO:root:WALLET_ENCRYPTION_PWD is not set

[ALERT]: WARNING:root:Ignoring usebtcfastsync option without Bitcoin selected.

[ALERT]: INFO:root:With coins: wownero, particl
INFO:root:prepareCore wownero v0.11.1.0

[ALERT]: INFO:root:Downloading file https://git.wownero.com/attachments/a1cf8611-1727-4b49-a8e5-1c66fe4f72a3
INFO:root:To C:\Users\TRISMEGISTUS\Desktop\BS\coindata\bin\wownero\wownero-0.11.1.0-win64.zip

[ALERT]: INFO:root:   62%  32.83 Mbps

[ALERT]: INFO:root:  100%  64.13 Mbps

[ALERT]: INFO:root:Downloading file https://git.wownero.com/wownero/wownero.org-website/raw/commit/97e100e1605e9f59bc8ca82a5b237d5562c8a21c/hashes.txt

[ALERT]: INFO:root:To C:\Users\TRISMEGISTUS\Desktop\BS\coindata\bin\wownero\wownero-0.11.1.0-hashes.txt

[ALERT]: INFO:root:  413%  74.80 kbps

[ALERT]: INFO:root:  825%  32.77 Mbps

[ALERT]: INFO:root:wownero-0.11.1.0-win64.zip hash: ba4c51fc7b802096497d171823a107e9c6a90f6cfd0396acb0b876a08834eb49

[ALERT]: INFO:root:Found release hash in assert file.

[ALERT]: ERROR:gnupg:Unable to run gpg (gpg) - it may not be available.
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\gnupg.py", line 1094, in __init__
    p = self._open_subprocess(['--list-config', '--with-colons'])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\gnupg.py", line 1164, in _open_subprocess
    result = Popen(cmd, shell=False, stdin=PIPE, stdout=PIPE, stderr=PIPE, startupinfo=si, env=self.env)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

[ALERT]: Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\gnupg.py", line 1094, in __init__
    p = self._open_subprocess(['--list-config', '--with-colons'])

[ALERT]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\gnupg.py", line 1164, in _open_subprocess

[ALERT]:     result = Popen(cmd, shell=False, stdin=PIPE, stdout=PIPE, stderr=PIPE, startupinfo=si, env=self.env)

[ALERT]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\subprocess.py", line 1026, in __init__

[ALERT]:     self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python312\Lib\subprocess.py", line 1538, in _execute_child

[ALERT]:     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\basicswap-prepare.exe\__main__.py", line 7, in <module>

[ALERT]:   File "C:\Python312\Lib\site-packages\bin\basicswap_prepare.py", line 2138, in main

[ALERT]:     prepareCore(c, known_coins[c], settings, data_dir, extra_opts)

[ALERT]:   File "C:\Python312\Lib\site-packages\bin\basicswap_prepare.py", line 830, in prepareCore

[ALERT]:     gpg = gnupg.GPG()
          ^^^^^^^^^^^

[ALERT]:   File "C:\Python312\Lib\site-packages\gnupg.py", line 1098, in __init__

[ALERT]:     raise OSError(msg)
OSError: Unable to run gpg (gpg) - it may not be available.

[INFO] BasicSwap setup completed.
[INFO] Setup and installation completed.
Second script exited with code 0

Screenshot:
![BS_Run](https://github.com/user-attachments/assets/b3704e0f-d537-46a0-bc81-cdec050a415b)

**Comment by absywabsy** [comment]
Hello, can anyone help me? I'm also stuck at 70% with the Windows v3.1.0

`[ALERT]: LogMessage : Error occurred during basicswap-prepare execution for Monero: The term 'basicswap-prepare' is not 
recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if 
a path was included, verify that the path is correct and try again.
At C:\Users\Abs\Downloads\basicswap-installer-win32-x64-v3.1.0-PRE-WIN\basicswap-installer-win32-x64\resources\app\buil

[ALERT]: d\part2-install.ps1:135 char:13
+             LogMessage "Error occurred during basicswap-prepare execu ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,LogMessage
 

Second script exited with code 1`
